package ch.maak.wz.communitylevels.communitylevels.shared.level;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

import javax.annotation.Generated;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.maak.wz.communitylevels.communitylevels.client.level.LevelIdForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class LevelIdFormData extends AbstractFormData {
    private static final long serialVersionUID = 1L;

    public LevelId getLevelId() {
        return getFieldByClass(LevelId.class);
    }

    public static class LevelId extends AbstractValueFieldData<String> {
        private static final long serialVersionUID = 1L;
    }
}
