package ch.maak.wl.communitylevels.communitylevels.shared.level;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@Generated(value = "ch.maak.wl.communitylevels.communitylevels.client.level.AllLevelTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AllLevelTablePageData extends AbstractLevelTablePageData {

	private static final long serialVersionUID = 1L;

	@Override
	public AllLevelTableRowData addRow() {
		return (AllLevelTableRowData) super.addRow();
	}

	@Override
	public AllLevelTableRowData addRow(int rowState) {
		return (AllLevelTableRowData) super.addRow(rowState);
	}

	@Override
	public AllLevelTableRowData createRow() {
		return new AllLevelTableRowData();
	}

	@Override
	public Class<? extends AbstractTableRowData> getRowType() {
		return AllLevelTableRowData.class;
	}

	@Override
	public AllLevelTableRowData[] getRows() {
		return (AllLevelTableRowData[]) super.getRows();
	}

	@Override
	public AllLevelTableRowData rowAt(int index) {
		return (AllLevelTableRowData) super.rowAt(index);
	}

	public void setRows(AllLevelTableRowData[] rows) {
		super.setRows(rows);
	}

	public static class AllLevelTableRowData extends AbstractLevelTableRowData {

		private static final long serialVersionUID = 1L;
	}
}
