package ch.maak.wl.communitylevels.communitylevels.shared.level;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@ClassId("81ce2baa-b4fc-4de9-8095-2c1fd33b9eb9-formdata")
@Generated(value = "ch.maak.wl.communitylevels.communitylevels.client.level.MostDifficultLevelTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class MostDifficultLevelTablePageData extends AbstractLevelTablePageData {

	private static final long serialVersionUID = 1L;

	@Override
	public MostDifficultLevelTableRowData addRow() {
		return (MostDifficultLevelTableRowData) super.addRow();
	}

	@Override
	public MostDifficultLevelTableRowData addRow(int rowState) {
		return (MostDifficultLevelTableRowData) super.addRow(rowState);
	}

	@Override
	public MostDifficultLevelTableRowData createRow() {
		return new MostDifficultLevelTableRowData();
	}

	@Override
	public Class<? extends AbstractTableRowData> getRowType() {
		return MostDifficultLevelTableRowData.class;
	}

	@Override
	public MostDifficultLevelTableRowData[] getRows() {
		return (MostDifficultLevelTableRowData[]) super.getRows();
	}

	@Override
	public MostDifficultLevelTableRowData rowAt(int index) {
		return (MostDifficultLevelTableRowData) super.rowAt(index);
	}

	public void setRows(MostDifficultLevelTableRowData[] rows) {
		super.setRows(rows);
	}

	public static class MostDifficultLevelTableRowData extends AbstractLevelTableRowData {

		private static final long serialVersionUID = 1L;
	}
}
