package ch.maak.wl.communitylevels.communitylevels.shared.level;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications
 * recommended.
 */
@ClassId("0f93b818-06d1-4cfe-af88-409c50498a2a-formdata")
@Generated(value = "ch.maak.wl.communitylevels.communitylevels.client.player.PlayerTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PlayerTablePageData extends AbstractTablePageData {

	private static final long serialVersionUID = 1L;

	@Override
	public PlayerTableRowData addRow() {
		return (PlayerTableRowData) super.addRow();
	}

	@Override
	public PlayerTableRowData addRow(int rowState) {
		return (PlayerTableRowData) super.addRow(rowState);
	}

	@Override
	public PlayerTableRowData createRow() {
		return new PlayerTableRowData();
	}

	@Override
	public Class<? extends AbstractTableRowData> getRowType() {
		return PlayerTableRowData.class;
	}

	@Override
	public PlayerTableRowData[] getRows() {
		return (PlayerTableRowData[]) super.getRows();
	}

	@Override
	public PlayerTableRowData rowAt(int index) {
		return (PlayerTableRowData) super.rowAt(index);
	}

	public void setRows(PlayerTableRowData[] rows) {
		super.setRows(rows);
	}

	public static class PlayerTableRowData extends AbstractTableRowData {

		private static final long serialVersionUID = 1L;
		public static final String playerId = "playerId";
		public static final String rank = "rank";
		public static final String playerName = "playerName";
		public static final String records = "records";
		public static final String points = "points";
		private String m_playerId;
		private String m_rank;
		private String m_playerName;
		private Long m_records;
		private BigDecimal m_points;

		public String getPlayerId() {
			return m_playerId;
		}

		public void setPlayerId(String newPlayerId) {
			m_playerId = newPlayerId;
		}

		public String getRank() {
			return m_rank;
		}

		public void setRank(String newRank) {
			m_rank = newRank;
		}

		public String getPlayerName() {
			return m_playerName;
		}

		public void setPlayerName(String newPlayerName) {
			m_playerName = newPlayerName;
		}

		public Long getRecords() {
			return m_records;
		}

		public void setRecords(Long newRecords) {
			m_records = newRecords;
		}

		public BigDecimal getPoints() {
			return m_points;
		}

		public void setPoints(BigDecimal newPoints) {
			m_points = newPoints;
		}
	}
}
